# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: myaction
on:
  push:
    branches: [ mergeAboutFeature , newFeature , testFeature ]
  pull_request:
    branches: [ mergeAboutFeature , newFeature , testFeature ]
jobs:
  run_tests:
    name: Test for the branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
  automerge:
    name: Auto merge after successful checks
    runs-on: ubuntu-latest
    steps:       
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: rebase
          target: 'newFeature'
